from distutils.core import setup

setup(
    name='bucket-list-flask-api',
    version='1.0',
    packages=['app', 'app.models', 'venv.lib.python3.5.distutils', 'venv.lib.python3.5.encodings',
              'venv.lib.python3.5.importlib', 'venv.lib.python3.5.collections', 'venv.lib.python3.5.site-packages.py',
              'venv.lib.python3.5.site-packages.py._io', 'venv.lib.python3.5.site-packages.py._log',
              'venv.lib.python3.5.site-packages.py._code', 'venv.lib.python3.5.site-packages.py._path',
              'venv.lib.python3.5.site-packages.py._process', 'venv.lib.python3.5.site-packages.jwt',
              'venv.lib.python3.5.site-packages.jwt.contrib', 'venv.lib.python3.5.site-packages.jwt.contrib.algorithms',
              'venv.lib.python3.5.site-packages.pbr', 'venv.lib.python3.5.site-packages.pbr.cmd',
              'venv.lib.python3.5.site-packages.pbr.hooks', 'venv.lib.python3.5.site-packages.pbr.tests',
              'venv.lib.python3.5.site-packages.pbr.tests.testpackage.pbr_testpackage',
              'venv.lib.python3.5.site-packages.pip', 'venv.lib.python3.5.site-packages.pip.req',
              'venv.lib.python3.5.site-packages.pip.vcs', 'venv.lib.python3.5.site-packages.pip.utils',
              'venv.lib.python3.5.site-packages.pip.compat', 'venv.lib.python3.5.site-packages.pip.models',
              'venv.lib.python3.5.site-packages.pip._vendor', 'venv.lib.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.5.site-packages.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip._vendor.requests',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip.commands', 'venv.lib.python3.5.site-packages.pip.operations',
              'venv.lib.python3.5.site-packages.boto', 'venv.lib.python3.5.site-packages.boto.gs',
              'venv.lib.python3.5.site-packages.boto.s3', 'venv.lib.python3.5.site-packages.boto.ec2',
              'venv.lib.python3.5.site-packages.boto.ec2.elb', 'venv.lib.python3.5.site-packages.boto.ec2.autoscale',
              'venv.lib.python3.5.site-packages.boto.ec2.cloudwatch', 'venv.lib.python3.5.site-packages.boto.ecs',
              'venv.lib.python3.5.site-packages.boto.emr', 'venv.lib.python3.5.site-packages.boto.fps',
              'venv.lib.python3.5.site-packages.boto.iam', 'venv.lib.python3.5.site-packages.boto.kms',
              'venv.lib.python3.5.site-packages.boto.mws', 'venv.lib.python3.5.site-packages.boto.rds',
              'venv.lib.python3.5.site-packages.boto.sdb', 'venv.lib.python3.5.site-packages.boto.sdb.db',
              'venv.lib.python3.5.site-packages.boto.sdb.db.manager', 'venv.lib.python3.5.site-packages.boto.ses',
              'venv.lib.python3.5.site-packages.boto.sns', 'venv.lib.python3.5.site-packages.boto.sqs',
              'venv.lib.python3.5.site-packages.boto.sts', 'venv.lib.python3.5.site-packages.boto.swf',
              'venv.lib.python3.5.site-packages.boto.vpc', 'venv.lib.python3.5.site-packages.boto.file',
              'venv.lib.python3.5.site-packages.boto.logs', 'venv.lib.python3.5.site-packages.boto.rds2',
              'venv.lib.python3.5.site-packages.boto.mturk', 'venv.lib.python3.5.site-packages.boto.pyami',
              'venv.lib.python3.5.site-packages.boto.pyami.installers',
              'venv.lib.python3.5.site-packages.boto.pyami.installers.ubuntu',
              'venv.lib.python3.5.site-packages.boto.manage', 'venv.lib.python3.5.site-packages.boto.roboto',
              'venv.lib.python3.5.site-packages.boto.cacerts', 'venv.lib.python3.5.site-packages.boto.cognito',
              'venv.lib.python3.5.site-packages.boto.cognito.sync',
              'venv.lib.python3.5.site-packages.boto.cognito.identity', 'venv.lib.python3.5.site-packages.boto.contrib',
              'venv.lib.python3.5.site-packages.boto.glacier', 'venv.lib.python3.5.site-packages.boto.kinesis',
              'venv.lib.python3.5.site-packages.boto.mashups', 'venv.lib.python3.5.site-packages.boto.route53',
              'venv.lib.python3.5.site-packages.boto.route53.domains', 'venv.lib.python3.5.site-packages.boto.support',
              'venv.lib.python3.5.site-packages.boto.cloudhsm', 'venv.lib.python3.5.site-packages.boto.dynamodb',
              'venv.lib.python3.5.site-packages.boto.opsworks', 'venv.lib.python3.5.site-packages.boto.redshift',
              'venv.lib.python3.5.site-packages.boto.services', 'venv.lib.python3.5.site-packages.boto.vendored',
              'venv.lib.python3.5.site-packages.boto.vendored.regions',
              'venv.lib.python3.5.site-packages.boto.awslambda', 'venv.lib.python3.5.site-packages.boto.beanstalk',
              'venv.lib.python3.5.site-packages.boto.dynamodb2', 'venv.lib.python3.5.site-packages.boto.cloudfront',
              'venv.lib.python3.5.site-packages.boto.cloudtrail', 'venv.lib.python3.5.site-packages.boto.codedeploy',
              'venv.lib.python3.5.site-packages.boto.cloudsearch', 'venv.lib.python3.5.site-packages.boto.elasticache',
              'venv.lib.python3.5.site-packages.boto.cloudsearch2',
              'venv.lib.python3.5.site-packages.boto.datapipeline',
              'venv.lib.python3.5.site-packages.boto.configservice',
              'venv.lib.python3.5.site-packages.boto.directconnect',
              'venv.lib.python3.5.site-packages.boto.cloudformation',
              'venv.lib.python3.5.site-packages.boto.machinelearning',
              'venv.lib.python3.5.site-packages.boto.cloudsearchdomain',
              'venv.lib.python3.5.site-packages.boto.elastictranscoder',
              'venv.lib.python3.5.site-packages.boto.ec2containerservice', 'venv.lib.python3.5.site-packages.cffi',
              'venv.lib.python3.5.site-packages.enum', 'venv.lib.python3.5.site-packages.idna',
              'venv.lib.python3.5.site-packages.mako', 'venv.lib.python3.5.site-packages.mako.ext',
              'venv.lib.python3.5.site-packages.mock', 'venv.lib.python3.5.site-packages.mock.tests',
              'venv.lib.python3.5.site-packages.nose', 'venv.lib.python3.5.site-packages.nose.ext',
              'venv.lib.python3.5.site-packages.nose.tools', 'venv.lib.python3.5.site-packages.nose.sphinx',
              'venv.lib.python3.5.site-packages.nose.plugins', 'venv.lib.python3.5.site-packages.pytz',
              'venv.lib.python3.5.site-packages.test', 'venv.lib.python3.5.site-packages.yaml',
              'venv.lib.python3.5.site-packages.click', 'venv.lib.python3.5.site-packages.flask',
              'venv.lib.python3.5.site-packages.flask.ext', 'venv.lib.python3.5.site-packages.isort',
              'venv.lib.python3.5.site-packages.pause', 'venv.lib.python3.5.site-packages.wheel',
              'venv.lib.python3.5.site-packages.wheel.test',
              'venv.lib.python3.5.site-packages.wheel.test.simple.dist.simpledist',
              'venv.lib.python3.5.site-packages.wheel.test.complex-dist.complexdist',
              'venv.lib.python3.5.site-packages.wheel.tool', 'venv.lib.python3.5.site-packages.wheel.signatures',
              'venv.lib.python3.5.site-packages.wrapt', 'venv.lib.python3.5.site-packages.bcrypt',
              'venv.lib.python3.5.site-packages.djmail', 'venv.lib.python3.5.site-packages.djmail.backends',
              'venv.lib.python3.5.site-packages.djmail.management',
              'venv.lib.python3.5.site-packages.djmail.management.commands',
              'venv.lib.python3.5.site-packages.djmail.migrations',
              'venv.lib.python3.5.site-packages.djmail.south_migrations', 'venv.lib.python3.5.site-packages.jinja2',
              'venv.lib.python3.5.site-packages.pyasn1', 'venv.lib.python3.5.site-packages.pyasn1.type',
              'venv.lib.python3.5.site-packages.pyasn1.codec', 'venv.lib.python3.5.site-packages.pyasn1.codec.ber',
              'venv.lib.python3.5.site-packages.pyasn1.codec.cer', 'venv.lib.python3.5.site-packages.pyasn1.codec.der',
              'venv.lib.python3.5.site-packages.pyasn1.codec.native', 'venv.lib.python3.5.site-packages.pyasn1.compat',
              'venv.lib.python3.5.site-packages.pylint', 'venv.lib.python3.5.site-packages.pylint.test.data',
              'venv.lib.python3.5.site-packages.pylint.test.input',
              'venv.lib.python3.5.site-packages.pylint.test.input.func_w0401_package',
              'venv.lib.python3.5.site-packages.pylint.test.extensions',
              'venv.lib.python3.5.site-packages.pylint.test.functional',
              'venv.lib.python3.5.site-packages.pylint.test.regrtest_data.dummy',
              'venv.lib.python3.5.site-packages.pylint.test.regrtest_data.absimp',
              'venv.lib.python3.5.site-packages.pylint.test.regrtest_data.package',
              'venv.lib.python3.5.site-packages.pylint.test.regrtest_data.package.subpackage',
              'venv.lib.python3.5.site-packages.pylint.test.regrtest_data.beyond_top',
              'venv.lib.python3.5.site-packages.pylint.test.regrtest_data.bad_package',
              'venv.lib.python3.5.site-packages.pylint.test.regrtest_data.package_all',
              'venv.lib.python3.5.site-packages.pylint.checkers', 'venv.lib.python3.5.site-packages.pylint.pyreverse',
              'venv.lib.python3.5.site-packages.pylint.reporters',
              'venv.lib.python3.5.site-packages.pylint.reporters.ureports',
              'venv.lib.python3.5.site-packages.pylint.extensions', 'venv.lib.python3.5.site-packages._pytest',
              'venv.lib.python3.5.site-packages._pytest._code', 'venv.lib.python3.5.site-packages._pytest.assertion',
              'venv.lib.python3.5.site-packages._pytest.vendored_packages', 'venv.lib.python3.5.site-packages.alembic',
              'venv.lib.python3.5.site-packages.alembic.ddl', 'venv.lib.python3.5.site-packages.alembic.util',
              'venv.lib.python3.5.site-packages.alembic.script', 'venv.lib.python3.5.site-packages.alembic.runtime',
              'venv.lib.python3.5.site-packages.alembic.testing',
              'venv.lib.python3.5.site-packages.alembic.testing.plugin',
              'venv.lib.python3.5.site-packages.alembic.operations',
              'venv.lib.python3.5.site-packages.alembic.autogenerate', 'venv.lib.python3.5.site-packages.astroid',
              'venv.lib.python3.5.site-packages.astroid.tests',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.SSL1',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.appl',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.lmfp',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.absimp',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.absimp.sidepackage',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.foogle.fax',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.package.subpackage',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.find_test',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.module1abs',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.path_pkgutil_1.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.path_pkgutil_2.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.path_pkgutil_3.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.unicode_package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.unicode_package.core',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.path_pkg_resources_1.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.path_pkg_resources_2.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python2.data.path_pkg_resources_3.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.SSL1',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.appl',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.lmfp',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.absimp',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.absimp.sidepackage',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.foogle.fax',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.package.subpackage',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.find_test',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.module1abs',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.path_pkgutil_1.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.path_pkgutil_2.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.path_pkgutil_3.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.unicode_package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.unicode_package.core',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.path_pkg_resources_1.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.path_pkg_resources_2.package',
              'venv.lib.python3.5.site-packages.astroid.tests.testdata.python3.data.path_pkg_resources_3.package',
              'venv.lib.python3.5.site-packages.astroid.interpreter',
              'venv.lib.python3.5.site-packages.astroid.interpreter._import',
              'venv.lib.python3.5.site-packages.certifi', 'venv.lib.python3.5.site-packages.chardet',
              'venv.lib.python3.5.site-packages.chardet.cli', 'venv.lib.python3.5.site-packages.mistune',
              'venv.lib.python3.5.site-packages.passlib', 'venv.lib.python3.5.site-packages.passlib.ext',
              'venv.lib.python3.5.site-packages.passlib.ext.django', 'venv.lib.python3.5.site-packages.passlib.tests',
              'venv.lib.python3.5.site-packages.passlib.utils', 'venv.lib.python3.5.site-packages.passlib.utils.compat',
              'venv.lib.python3.5.site-packages.passlib.crypto',
              'venv.lib.python3.5.site-packages.passlib.crypto.scrypt',
              'venv.lib.python3.5.site-packages.passlib.crypto._blowfish',
              'venv.lib.python3.5.site-packages.passlib.handlers', 'venv.lib.python3.5.site-packages.urllib3',
              'venv.lib.python3.5.site-packages.urllib3.util', 'venv.lib.python3.5.site-packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.5.site-packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.urllib3.packages.backports',
              'venv.lib.python3.5.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.coverage', 'venv.lib.python3.5.site-packages.dateutil',
              'venv.lib.python3.5.site-packages.dateutil.tz', 'venv.lib.python3.5.site-packages.dateutil.zoneinfo',
              'venv.lib.python3.5.site-packages.demo_app', 'venv.lib.python3.5.site-packages.examples',
              'venv.lib.python3.5.site-packages.flasgger', 'venv.lib.python3.5.site-packages.funcsigs',
              'venv.lib.python3.5.site-packages.gunicorn', 'venv.lib.python3.5.site-packages.gunicorn.app',
              'venv.lib.python3.5.site-packages.gunicorn.http', 'venv.lib.python3.5.site-packages.gunicorn.workers',
              'venv.lib.python3.5.site-packages.gunicorn.instrument',
              'venv.lib.python3.5.site-packages.gunicorn.management',
              'venv.lib.python3.5.site-packages.gunicorn.management.commands',
              'venv.lib.python3.5.site-packages.markdown', 'venv.lib.python3.5.site-packages.markdown.extensions',
              'venv.lib.python3.5.site-packages.psycopg2', 'venv.lib.python3.5.site-packages.psycopg2.tests',
              'venv.lib.python3.5.site-packages.requests', 'venv.lib.python3.5.site-packages.requests.packages',
              'venv.lib.python3.5.site-packages.requests.packages.chardet',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3.util',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.sendgrid', 'venv.lib.python3.5.site-packages.sendgrid.helpers',
              'venv.lib.python3.5.site-packages.sendgrid.helpers.mail',
              'venv.lib.python3.5.site-packages.sendgrid.helpers.inbound', 'venv.lib.python3.5.site-packages.werkzeug',
              'venv.lib.python3.5.site-packages.werkzeug.debug', 'venv.lib.python3.5.site-packages.werkzeug.contrib',
              'venv.lib.python3.5.site-packages.aniso8601', 'venv.lib.python3.5.site-packages.backports',
              'venv.lib.python3.5.site-packages.backports.configparser', 'venv.lib.python3.5.site-packages.coveralls',
              'venv.lib.python3.5.site-packages.flask_api', 'venv.lib.python3.5.site-packages.flask_api.tests',
              'venv.lib.python3.5.site-packages.flask_jwt', 'venv.lib.python3.5.site-packages.pycparser',
              'venv.lib.python3.5.site-packages.pycparser.ply', 'venv.lib.python3.5.site-packages.sgbackend',
              'venv.lib.python3.5.site-packages.flask_cors', 'venv.lib.python3.5.site-packages.jsonschema',
              'venv.lib.python3.5.site-packages.jsonschema.tests', 'venv.lib.python3.5.site-packages.markupsafe',
              'venv.lib.python3.5.site-packages.pytest_cov', 'venv.lib.python3.5.site-packages.setuptools',
              'venv.lib.python3.5.site-packages.setuptools.extern',
              'venv.lib.python3.5.site-packages.setuptools.command', 'venv.lib.python3.5.site-packages.simplejson',
              'venv.lib.python3.5.site-packages.simplejson.tests', 'venv.lib.python3.5.site-packages.sqlalchemy',
              'venv.lib.python3.5.site-packages.sqlalchemy.ext',
              'venv.lib.python3.5.site-packages.sqlalchemy.ext.declarative',
              'venv.lib.python3.5.site-packages.sqlalchemy.orm', 'venv.lib.python3.5.site-packages.sqlalchemy.sql',
              'venv.lib.python3.5.site-packages.sqlalchemy.util', 'venv.lib.python3.5.site-packages.sqlalchemy.event',
              'venv.lib.python3.5.site-packages.sqlalchemy.engine',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing.suite',
              'venv.lib.python3.5.site-packages.sqlalchemy.testing.plugin',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.mssql',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.mysql',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.oracle',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.sqlite',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.sybase',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.firebird',
              'venv.lib.python3.5.site-packages.sqlalchemy.dialects.postgresql',
              'venv.lib.python3.5.site-packages.sqlalchemy.databases',
              'venv.lib.python3.5.site-packages.sqlalchemy.connectors', 'venv.lib.python3.5.site-packages.whitenoise',
              'venv.lib.python3.5.site-packages.whitenoise.management',
              'venv.lib.python3.5.site-packages.whitenoise.management.commands',
              'venv.lib.python3.5.site-packages.flask_script', 'venv.lib.python3.5.site-packages.flask_migrate',
              'venv.lib.python3.5.site-packages.flask_restful', 'venv.lib.python3.5.site-packages.flask_restful.utils',
              'venv.lib.python3.5.site-packages.flask_restful.representations',
              'venv.lib.python3.5.site-packages.flask_testing', 'venv.lib.python3.5.site-packages.pkg_resources',
              'venv.lib.python3.5.site-packages.pkg_resources.extern',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor.packaging',
              'venv.lib.python3.5.site-packages.flask_restplus', 'venv.lib.python3.5.site-packages.flask_sqlalchemy',
              'venv.lib.python3.5.site-packages.lazy_object_proxy',
              'venv.lib.python3.5.site-packages.python_http_client',
              'venv.lib.python3.5.site-packages.sqlalchemy_paginator',
              'venv.lib.python3.5.site-packages.flask_restful_swagger',
              'venv.lib.python3.5.site-packages.flask_restful_swagger_2',
              'venv.lib.python3.5.site-packages.codeclimate_test_reporter',
              'venv.lib.python3.5.site-packages.codeclimate_test_reporter.components', 'tests_models',
              'tests_endpoints'],
    url='',
    license='',
    author='Josiah Nyarega',
    author_email='josiah.mokobo@andela.com',
    description='bucketlist api '
)
