"""empty message

Revision ID: bc200efbc1a5
Revises: 
Create Date: 2017-07-12 15:22:51.779627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc200efbc1a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlist',
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('bucket_name', sa.String(), nullable=True),
    sa.Column('bucket_descriptions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('bucket_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('bucketlist')
    # ### end Alembic commands ###
